# Generated by Django 3.0.5 on 2020-06-08 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='departamento',
        ),
        migrations.AddField(
            model_name='categoria',
            name='departamento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='core.Departamento', verbose_name='departamento'),
            preserve_default=False,
        ),
    ]
