# Generated by Django 3.0.5 on 2020-07-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200608_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='codigo',
            field=models.BigIntegerField(default=0, verbose_name='Código'),
            preserve_default=False,
        ),
    ]
