# Generated by Django 3.0.5 on 2020-07-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='codigo',
            field=models.BigIntegerField(unique=True, verbose_name='Código'),
        ),
    ]
